### ISSUE TITLE
Where to find PURE API documentation

### ISSUE THREAD

**Issue by adamjakab** [UMNLibraries/pureapi#6]
Hi! Could you please point me to the documentation you used to develop this application? I need to do something similar in Php. My university has a [Pure](https://www.elsevier.com/solutions/pure) implementation and I need to pull a list of authors and publications to display them on the website. Should be simple but when I go to https://dev.elsevier.com/ the product is not listed. 
I have an API key and when I hit the API endpoint /ws/api/513/research-outputs I get some responses but I am digging in the dark.

Thanks in advance

**Comment by nihiliad** [comment]
Happy to do so, Adam!

The most helpful documentation for me is Elsevier's interactive
documentation, which should be at: https://your.pure.domain/
ws/api/516/api-docs/index.html#/
<https://experts.umn.edu/ws/api/516/api-docs/index.html#/> The 516
specifies the version of the Pure API, in this case 5.16, which is what
we're using. As you may know, Elsevier is rolling out 5.17 to Staging
environments tomorrow, and to Production on March 12
https://doc.pure.elsevier.com/pages/viewpage.action?pageId=37685723. To use
the interactive docs as well as the API itself, you'll need to get an API
key from your Pure administrator. You may also notice that Elsevier uses
https://swagger.io/ to build the interactive docs. Therefore, your API
schema should be at: https://your.pure.domain/ws/api/516/swagger.json

Another great source of information is Pure support:
https://support.pure.elsevier.com/secure/Dashboard.jspa That's not only for
submitting bug reports, but also just asking questions. Elsevier has been
mostly very good at answering mine. Elsevier also provides this
documentation, which may be helpful:
https://doc.pure.elsevier.com/pages/viewpage.action?pageId=37685723

There are some great community resources, too. I suggest joining both the North
American Pure User (NAPUG) mailing list
<https://groups.google.com/forum/#!forum/NAPUG>, and:
https://pure-community.slack.com/

Finally, you're welcome to as me questions, too, especially about the
software we wrote here at UMN.

Good luck!

--
David Naughton
Web Development
University of Minnesota Libraries
naughton@umn.edu

**Comment by adamjakab** [comment]
Dear David! This is pure gold! Thanks a lot for this. 
Now I can work on this properly. 
Have a great day!

**Comment by nihiliad** [comment]
You're very welcome, Adam!

It's important to me to promote community among developers, so I'm glad you
found that helpful. When I first started working with Pure, I had a
difficult time finding documentation. I didn't always get great help with
that from Elsevier, either. I hope I can help to spare you some of the pain
I experienced.

I knew almost nothing about anything I was working with when I started this
project. I've mostly been the only developer, and have found it challenging
to keep my head above water. There's lots I want to improve in the pureapi
and other code I've written. I'm embarrassed at the current state of it. I
appreciate your feedback, because that's invaluable to help me do that. I
hope to have improvements to share soon!
